### ISSUE TITLE
Chrome OS Look

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Chrome-OS#1]
Two things might want to be implemented into the Chrome OS theme to make it more like the OS:
1. (afaik) Chrome/Chromium OS has a black line on the bottom of the panel where the running indicator is but behind the indicator so the theme might want to follow suit
2. Chrome OS has black text in windows (just look at Chrome OS Settings for example)
3. Headerbars are still Windows 10 Theme
4. Chrome OS has window buttons shaded on hover and press slightly

Apart from that, great theme! :)

**Comment by Elbullazul** [comment]
I don't get your first suggestion.  A black line at the bottom of the panel is missing,  is that it? 

Text color will be fixed in next release 

Thanks for your feedback :)

**Comment by cinnamoner** [comment]
@Guys 
Hello to you!

**Comment by dominichayesferen** [comment]
There's a black panel on the bottom part of the screen where the running indicator is also placed in Chrome OS except for it stretches across the whole panel, it might look better if the Cinnamon theme takes suit that way too.
![image](https://cloud.githubusercontent.com/assets/11057934/16330169/30cc183a-39df-11e6-9d67-0006516ee6a9.png)
See the black line at the bottom in that image? That's what I mean

**Comment by Elbullazul** [comment]
Ooh,  OK.  I hadn't seen that. 

I'll fix it.  Thanks again for the feedback

**Comment by dominichayesferen** [comment]
UPDATE: 5. Cinnamon notifications have white text on white BG, you know what that causes don't you?

**Comment by Elbullazul** [comment]
@feren I was sure I had pushed the updated version that fixed this error. 

I'll push the update as soon as I can

**Comment by dominichayesferen** [comment]
Yeah, 5 is fixed now, just tried a notify-send

**Comment by dominichayesferen** [comment]
...just not the black line at the bottom of the panel

**Comment by Elbullazul** [comment]
fixed all issues with R3

**Comment by dominichayesferen** [comment]
Cool. :)
