### ISSUE TITLE
Unable to locate image file in pixmap_path: "Panel/bc.png"

### ISSUE THREAD

**Issue by Mahi** [B00merang-Project/Chrome-OS#10]
When opening `gvim` from terminal, I get the following error message (vim opens just fine regardless of it):

    /home/mahi/.themes/Chrome OS/gtk-2.0/Apps/mintmenu.rc:3: Unable to locate image file in pixmap_path: "Panel/bc.png"

I'm running on Linux Mint 18 Cinnamon, and I'm only using Chrome OS for the "Controls" section from "Themes":

![image](https://cloud.githubusercontent.com/assets/11020883/24944106/404eb0a6-1f62-11e7-9aa2-d10a76297299.png)

**Update:** This seems to happen regardless of which program I open, tested with `gvim`, `git-cola`, and `chromium-browser`

**Comment by Elbullazul** [comment]
@Mahi I'll verify the bug. Does the error message say which file is affected?

**Comment by Mahi** [comment]
That's all it says:

/home/mahi/.themes/Chrome OS/gtk-2.0/Apps/mintmenu.rc:3: Unable to locate image file in pixmap_path: "Panel/bc.png"
