### ISSUE TITLE
[Evolution 3.24] Links are invisible (white on white)

### ISSUE THREAD

**Issue by HeikoAdams** [B00merang-Project/Chrome-OS#11]
Using latest git master links in text-mails are invisible in evolution because it seems they are white on white background.

![bildschirmfoto von 2017-05-31 17-21-22](https://cloud.githubusercontent.com/assets/1418818/26639706/e03b9ce8-4625-11e7-9806-74fb86a4dd9f.png)

**Comment by Elbullazul** [comment]
fixed
