### ISSUE TITLE
gtk3: scroll bar is too thick and (color) not clearly visible

### ISSUE THREAD

**Issue by gps08** [B00merang-Project/Chrome-OS#17]
can ignore this issue of you want, its just a suggestion to look better.

**Comment by Elbullazul** [comment]
![orig-scrollbar](https://cnet3.cbsistatic.com/img/oI5sWegfJM03YYawZXD2vp6OH74=/fit-in/770x578/2017/03/09/d0c24bf7-c1b2-47ee-bde2-27a73bae2c14/google-chromeos-print-1.jpg)

seems like the original Chrome OS design is thick scrollbars, but I agree with you, they look out of place. Will probably slim them down a bit and increase contrast
