### ISSUE TITLE
Button borders in xfce-appfinder (gtk3.2)

### ISSUE THREAD

**Issue by gps08** [B00merang-Project/Chrome-OS#19]
![image](https://user-images.githubusercontent.com/19977242/27738235-68d1d234-5dc8-11e7-8dcd-85de37ba58d2.png)

i have checked with other gtk3.2 using windows and all have the same problem

**Comment by Elbullazul** [comment]
@gps08 what's the bug? I don't see it

**Comment by gps08** [comment]
![image](https://user-images.githubusercontent.com/19977242/27740749-99c5cef6-5dd0-11e7-8688-5b40d6631455.png)
I was thinking that there should be border on the close button like there is on the cancel button in the image
attached

**Comment by Elbullazul** [comment]
@gps08 regular Chrome OS buttons don't have borders:

![chrome-os-dialog](http://i.imgur.com/yWFH8p3.png)

the 2nd screenshot is a GTK 2 app, and GTK 2 doesn't allow for transparent borders ONLY for buttons. It's take all or none.

but those buttons should not be that apparent, maybe they should be transparent?

**Comment by gps08** [comment]
@Elbullazul  I dont know how it would look, mayb post a screenshot with transparent buttons?

**Comment by Elbullazul** [comment]
@gps08 this is android nougat:

![nougat-buttons](http://phandroid.s3.amazonaws.com/wp-content/uploads/2016/08/Nexus-6P-Nav-Bar-Customizer-Screenshot_20160824-004604.png)

and in Chrome OS:

![screenshot 2016-09-28 at 18 48 16](https://user-images.githubusercontent.com/15310985/27747480-4814b360-5d99-11e7-9c11-b8a89bcf336c.png)

**Comment by gps08** [comment]
@Elbullazul yes it would be real cool to have those if possible

**Comment by ghost** [comment]
I agree, material design relies on flat buttons if the surface it's on clearly supports the context for it. Primary or dangerous buttons should be raised but cancel buttons and the like shouldn't be, probably.
