### ISSUE TITLE
Chrome OS Look Suggestions (Updated)

### ISSUE THREAD

**Issue by dominichayesferen** [B00merang-Project/Chrome-OS#2]
1. Make the titlebars FULLY white (some Chrome Apps have white titlebars when they don't colour the titlebars themselves in Chrome OS, like this screenshot:
   ![image](https://cloud.githubusercontent.com/assets/11057934/18027982/c4b64e76-6c61-11e6-92ba-cb7093eaa443.png)
2. Make the titles themselves black rather than white **to make them legible**

**Comment by Elbullazul** [comment]
yeah, I'll have a look at this

btw do you prefer I focus on this or on longhorn themes?

**Comment by dominichayesferen** [comment]
@Elbullazul 
Probably Longhorn Themes...

**Comment by Elbullazul** [comment]
@feren fix implemented, coming soon...

**Comment by Elbullazul** [comment]
published with R5 : https://github.com/Elbullazul/Chromium-OS/releases/download/R5/Chrome.OS.R5.tar.gz

**Comment by ghost** [comment]
@Elbullazul Has been noticed. Good work. Yeah, I'd like some Longhorn me too.👍
