### ISSUE TITLE
Cinnamon Taskbar Text is Black

### ISSUE THREAD

**Issue by rahilwazir** [B00merang-Project/Chrome-OS#20]
The Cinnamon taskbar is very dark, the text is not visible at all.
![taskbar_gone_wild](https://user-images.githubusercontent.com/1818941/30058674-7772a4c8-9255-11e7-8d0a-4538e13863f8.png)

**Comment by dominichayesferen** [comment]
@rahilwazir To fix this, go into System Settings > Extensions > Online, and Install, and Enable 'Transparent Panels'

Make sure to also go in Transparent Panels Settings, and change it to 'Controlled by Theme'.

**Comment by rahilwazir** [comment]
Nope, still no success.

![gone_even_wild](https://user-images.githubusercontent.com/1818941/30060516-248b631e-925d-11e7-8242-07ee741e0b3c.png)

**Comment by dominichayesferen** [comment]
@rahilwazir Unmaximise the window, the point of it is to make it transparent WHEN the window isn't maximised

**Comment by rahilwazir** [comment]
Nah, I tried before submitting my previous comment, but here you go 😄 

![gone_even_wild](https://user-images.githubusercontent.com/1818941/30060711-f10a5102-925d-11e7-8e17-e32715bc402b.png)

**Comment by dominichayesferen** [comment]
Hmm... odd... :/

**Comment by dominichayesferen** [comment]
@Elbullazul

**Comment by rahilwazir** [comment]
Oh wait the background image was conflicting, changed my background. But still not readable 😭 

![gone_even_wild](https://user-images.githubusercontent.com/1818941/30060952-dda886fa-925e-11e7-8a6c-d91bd0a2ab09.png)

**Comment by dominichayesferen** [comment]
@rahilwazir For now, you can try out Icing Task Manager (System Settings > Applets > Online), it's an alternative to Window List but grouping + without text is an option.

**Comment by dominichayesferen** [comment]
Also, I'm jealous now, you've got that Mac OS X Theme that I can't use due to an outdated GTK...

**Comment by rahilwazir** [comment]
Thanks, that didn't work well though. Group icons and already opened apps looks messy in task bar 🌋. I think I'll use other theme for my taskbar until this is fixed 😞 

> Also, I'm jealous now, you've got that Mac OS X Theme that I can't use due to an outdated GTK...

Hah sorry, but when you have updated it try this: [Poppy OSX](https://www.opendesktop.org/p/1184644) not supported for cinnamon but very native feel than any other available OSX themes along with [Mavericks](https://www.gnome-look.org/content/show.php/Mavericks?content=174324).
**Cinnamon > Themes > Controls**: Poppy OSX , **Window borders**: Mavericks

**Comment by gps08** [comment]
[cinnamon.css.zip](https://github.com/B00merang-Project/Chrome-OS/files/1277609/cinnamon.css.zip)
@rahilwazir  try replacing this file in your {theme-directory}/Chrome-OS/cinnamon/ and see if it helps..

**Comment by rahilwazir** [comment]
@gps08 Thanks, but the text is still not visible as well the panel settings.

![fail](https://user-images.githubusercontent.com/1818941/30068076-06f5524c-9276-11e7-97c3-c522ec0accf7.png)

Can we just give highlight the background of the text so it will be visible regardless of background image?

**Comment by Elbullazul** [comment]
I have my dev environment offline for now, but the latest commit should change text color to white

also, for panel menu I need to test changes before I push them, so I'll have to restore my distro before searching a solution

for information, can you post the Linux distro you're using as well as the Cinnamon version?

**Comment by rahilwazir** [comment]
@Elbullazul Thanks for the commit but it's still NOT fixed. The color for both taskbar and panel are still black. I have checked out the latest https://github.com/B00merang-Project/Chrome-OS/commit/20aa998230fcd15cc2c87496eef86a22b50dbf36 commit (same result as above [recent] screenshot). Restarted desktop manager (<kbd>Alt</kbd>+<kbd>F2</kbd> and <kbd>r</kbd>) and also logged out as well! No luck 😢 

**Linux Distro:** Fedora 26
**Cinnamon:** v3.4.6

**Comment by dominichayesferen** [comment]
<kbd>CTRL</kbd> + <kbd>ALT</kbd> + <kbd>DEL</kbd> is quicker.

**Comment by rahilwazir** [comment]
@feren Thanks for it but it didn't help solving this issue :D

**Comment by Elbullazul** [comment]
@rahilwazir which cinnamon version are you using?

**Comment by dominichayesferen** [comment]
@Elbullazul Cinnamon: v3.4.6 (Kind of says so above)

**Comment by Elbullazul** [comment]
> @Elbullazul Cinnamon: v3.4.6 (Kind of says so above)

sorry, didn't see that

will exmaine in the coming week

**Comment by dominichayesferen** [comment]
@rahilwazir What is that Metacity Theme you use in conjunction with Poppy OSX Revive?
