### ISSUE TITLE
Add Dash to Panel Support for Gnome

### ISSUE THREAD

**Issue by Carbongrip** [B00merang-Project/Chrome-OS#21]
Hello, please add support for Dash to Panel on Gnome. It's similar to Dash to Dock but uses the Gnome panel instead of the Activities Dash.
![screenshot](https://user-images.githubusercontent.com/33745827/36581654-424af730-182b-11e8-8903-c5bf3c3d375a.png)
[https://github.com/jderose9/dash-to-panel](https://github.com/jderose9/dash-to-panel)

Then you can get added to the Supported Themes Section on the Github Page
> Themes
> 
> While this extension works well with most popular Gnome Shell themes, the following themes are known to have explicitly added custom styles for this extension:
> 
>     Ciliora Tertia / Ciliora Secunda
>     Plano

Here is an example of the theme code for Dash to Panel...
`/* ======================================
 * ! Dash-to-Panel extension
 * ====================================== */
#panel.dashtopanelMainPanel.dashtopanelTop {
  border-image: url("img/panel/panel-top.svg") 7;
}

#panel.dashtopanelMainPanel.dashtopanelTop .app-well-app-running-dot {
  width: 0;
  height: 0;
  border-image: none;
  background-color: transparent;
  border: 0;
}`

**Comment by Elbullazul** [comment]
Thanks for the suggestion, will implement but can't say when

**Comment by Elbullazul** [comment]
Seems like dash to panel implemented the default classes, as it looks pretty good at the moment:
![image](https://user-images.githubusercontent.com/15310985/101283973-b0cb9780-37ab-11eb-99c0-6a920b97b7bc.png)
