### ISSUE TITLE
Chrome OS on Cinnamon Spices

### ISSUE THREAD

**Issue by smurphos** [B00merang-Project/Chrome-OS#22]
@Elbullazul 

Hi,

I've been checking out some of the themes on Cinnamon Spices compatibility for GTK 3.22 environments and the forthcoming Cinnamon 3.8. I'm not a team member of there but an occasional contributor.

The version of Chrome OS at https://github.com/linuxmint/cinnamon-spices-themes/tree/master/ChromeOS has broken theming in a GTK3.22 environment. I can see that the version here is maintained so could you raise a PR to bring the spices version in line?

Also it looks like that from Cinnamon 3.8 the Muffin Window Manager will stop supporting version 1 metacity themes so the existing Metacity theme will not be available to select in the themes app.

Cheers.

**Comment by Elbullazul** [comment]
Will update metacity theme and include newest GTK theme, possibly this week or next

**Comment by Elbullazul** [comment]
Update: We're not updating our themes on cinnamon spices anymore

**Comment by smurphos** [comment]
Any objection if I keep the Spices version up to date with your upstream? Or would you prefer for them to be removed?

**Comment by Elbullazul** [comment]
@smurphos you can do that if you want, yes.

**Comment by smurphos** [comment]
Thanks - I'll look at further updating the Cinnamon themes to take advantage of current Cinnamon features and will PR back as I go along...
