### ISSUE TITLE
Not compatible with GTK 3.22

### ISSUE THREAD

**Issue by Vistaus** [B00merang-Project/Chrome-OS#3]
Thank you so much! Finally someone who created a real, slick ChromeOS theme for Linux! :smile: 
Unfortunately though, it's not compatible with 3.22; everything looks garbled. Could you please update it so that I can start using this awesome theme?

**Comment by Elbullazul** [comment]
shure. We'll start the porting process in a couple of days, and then we'll have to gear everything up for it to look nice again. I'll let you know when the 3.20 version is ready

thanks for your interest in this theme :smiley:

**Comment by Vistaus** [comment]
Thank you for the fast response and thanks in advance for letting me know when it's ready, I'll wait patiently! :smile:

**Comment by Elbullazul** [comment]
Chrome OS theme is now compatible with GTK 3.20 and superior
[get latest here](https://github.com/B00merang-Project/Chrome-OS/releases/tag/R7)

**Comment by cinnamoner** [comment]
Don't say! Hmmm. A real treat.

**Comment by Vistaus** [comment]
Yeaahhhh thank you so much! I'm so happy right now! :smile:  Although there is a tiny issue but I'll open up  a new issue for that. But again: thank you so much! :smile:
