### ISSUE TITLE
Fonts look washed out in some apps

### ISSUE THREAD

**Issue by Vistaus** [B00merang-Project/Chrome-OS#4]
Now that the theme is finally compatible with GTK 3.22 ( :smile: ) I can finally start using it. But there's a tiny issue though with the fonts: they look washed out in some apps. I'll attach two screenshots where you can see the problem. It's mostly in the headerbars and sidebars.

![screenshot from 2016-10-19 10-48-02](https://cloud.githubusercontent.com/assets/1716229/19511947/ec026ba2-95e9-11e6-806d-5ff60bbd8e18.png)
![screenshot from 2016-10-19 10-46-51](https://cloud.githubusercontent.com/assets/1716229/19511948/ec078240-95e9-11e6-9cc6-b1cad22f045e.png)

Edit: the same problem is present in the dark version: the fonts are unreadable in the dark version because they look washed out.

**Comment by Elbullazul** [comment]
ok. I'll fix this as soon as possible

**Comment by Elbullazul** [comment]
found the issue, but my laptop's cord died two hours ago :disappointed: 

updating as soon as possible, thanks for your patience :)

**Comment by Vistaus** [comment]
I'm sorry to hear that! :disappointed: I hope you'll be able to get a new one soon! In the meantime, I'll keep waiting patiently :smile_cat:

**Comment by Elbullazul** [comment]
wait no more, R8 is waiting for you... :smiley: 

https://github.com/B00merang-Project/Chrome-OS/releases/tag/R8

**Comment by Vistaus** [comment]
It really is fixed! Thank you so much!!! :smile:

**Comment by Elbullazul** [comment]
you're welcome, it's a pleasure to open the bug hunting season with a kill :+1:
