### ISSUE TITLE
Gnome-Shell Theme?

### ISSUE THREAD

**Issue by HeikoAdams** [B00merang-Project/Chrome-OS#5]
Which Gnome-Shell theme do you recommend for using with your theme or do you plan the develop your own gs-theme?

**Comment by dominichayesferen** [comment]
@HeikoAdams I'd try one that's completely transparent, and then goes opaque when a window is maximized

**Comment by Elbullazul** [comment]
@HeikoAdams we're planning on eventually integrate a shell theme. Meanwhile, I think you can use [this one](https://www.gnome-look.org/p/1013030/), that looks close enough

**Comment by Vistaus** [comment]
Yay, great to see you're planning a Shell theme as well! :smile:

**Comment by Elbullazul** [comment]
ok, we have one in beta, still some things to be fixed, but overall it looks like chrome os would

also planning on updating those checkboxes assets that look like they come from the past century...

**Comment by Vistaus** [comment]
Awesome! Looking forward to try the GS theme soon! :smile_cat:

**Comment by Elbullazul** [comment]
it's now pushed to the repo. You can try it @HeikoAdams @Vistaus

**Comment by Vistaus** [comment]
Awesome! I'll try it out asap! :smile:
