### ISSUE TITLE
Chrome OS Theme on Ubuntu GNOME (devel branch)

### ISSUE THREAD

**Issue by brandleesee** [B00merang-Project/Chrome-OS#6]
Gnome Shell version: 3.22.1

**Remark for White Theme**
While using the White Theme I noticed that white background against grey sections and a light font make for a dull visual experience. in short, I think the shades chosen can be improved.

**Remark for Global Dark Theme swithced ON**
The light font against a dark grey background is both hard to see as well as mismatching. 
# Squashed Menus

![screenshot from 2016-10-27 17-40-44](https://cloud.githubusercontent.com/assets/12674437/19774634/10ba2c66-9c6e-11e6-8413-efcd2930a1a2.png)
Albeit sectioned, menu is sandwiched.

![screenshot from 2016-10-27 17-34-48](https://cloud.githubusercontent.com/assets/12674437/19774637/10feacb0-9c6e-11e6-89be-c353cbb2a0ed.png)

![screenshot from 2016-10-27 17-34-36](https://cloud.githubusercontent.com/assets/12674437/19774638/1101b98c-9c6e-11e6-8b85-c2a569bd6428.png)

![screenshot from 2016-10-27 17-44-25](https://cloud.githubusercontent.com/assets/12674437/19774689/42f2ce4a-9c6e-11e6-80d2-6080dee15afe.png)
In Dark theme, too.
# Lack of space

![screenshot from 2016-10-27 17-37-09](https://cloud.githubusercontent.com/assets/12674437/19774631/103f58b0-9c6e-11e6-9f36-479fc732af7e.png)
Programming Mode is too near the radio button.
# Glow too pronounced

![screenshot from 2016-10-27 17-43-03](https://cloud.githubusercontent.com/assets/12674437/19774691/431e146a-9c6e-11e6-8148-cc8b80a282a9.png)
Too white-ish and area of glow is large.
# Radio Buttons

![screenshot from 2016-10-27 17-44-43](https://cloud.githubusercontent.com/assets/12674437/19774687/42ed1874-9c6e-11e6-8525-86a90e80f0c6.png)
In Dark theme radio buttons are pixelated, so-to-speak.
# Font Colors, Lines & Bars

![screenshot from 2016-10-27 17-38-35](https://cloud.githubusercontent.com/assets/12674437/19774633/10b186d8-9c6e-11e6-9699-42d47bf4d7fc.png)
Font-color of title bar is too light against the white background. Compare with menu font-color.

![screenshot from 2016-10-27 17-37-39](https://cloud.githubusercontent.com/assets/12674437/19774629/1004fc10-9c6e-11e6-9053-2fdaddcc8c8e.png)
Font-color against orange background. Suggest black font.

![screenshot from 2016-10-27 17-36-32](https://cloud.githubusercontent.com/assets/12674437/19774632/107ecefa-9c6e-11e6-8aaa-de0d3e0b06b3.png)
Fonts of both titlebar and window and **progress indicator colour**. Suggest a darker shade of grey (lol)

![screenshot from 2016-10-27 17-35-33](https://cloud.githubusercontent.com/assets/12674437/19774636/10cc135e-9c6e-11e6-9369-1182d721309c.png)
Font against blue highlighting background. Suggest darker shade.

![screenshot from 2016-10-27 17-34-19](https://cloud.githubusercontent.com/assets/12674437/19774639/1105ef5c-9c6e-11e6-883d-2904ea391cea.png)
Look for mouse pointer. Note white font against grey background and **two blue lines above and below button**.

![screenshot from 2016-10-27 17-45-02](https://cloud.githubusercontent.com/assets/12674437/19774686/42e3010e-9c6e-11e6-8f56-6ddbf856fa32.png)
Light font against blue background.

![screenshot from 2016-10-27 17-44-06](https://cloud.githubusercontent.com/assets/12674437/19774688/42f06ab0-9c6e-11e6-92f2-e031495274b4.png)

![screenshot from 2016-10-27 17-42-38](https://cloud.githubusercontent.com/assets/12674437/19774692/4329dc6e-9c6e-11e6-91f1-b53536cc7eaa.png)
A light font against dark grey do not seem to match. Also, hard to see in terms of coloration.

![screenshot from 2016-10-27 17-42-22](https://cloud.githubusercontent.com/assets/12674437/19774693/43300af8-9c6e-11e6-842b-3cf7a218c5ac.png)

![screenshot from 2016-10-27 17-42-03](https://cloud.githubusercontent.com/assets/12674437/19774694/4338d926-9c6e-11e6-90b6-8a51156134b4.png)
# Terminal
### White Theme

![screenshot from 2016-10-27 17-41-10](https://cloud.githubusercontent.com/assets/12674437/19774635/10bb519a-9c6e-11e6-9942-bfeb64977579.png)
### Dark Theme

![screenshot from 2016-10-27 17-43-50](https://cloud.githubusercontent.com/assets/12674437/19774690/42f6f358-9c6e-11e6-9b58-8462adb756ea.png)

Correct me if I'm wrong but I think the terminal is governed by the shell. i.e. all good here!

**Comment by Elbullazul** [comment]
@brandleesee thanks for your feedback!

we'll tackle that problem as soon as possible. The last issue is (again) because of the dark-mode enabled in some apps for gnome

**Comment by brandleesee** [comment]
I still can't wrap my head around this dark-mode enabled in some apps for gnome.
Just for myself to understand once and for all: this is something that with Global Dark Theme ON or OFF makes no difference, right?
Also, I did Alt+F2 each time I switched GDT On/Off, you know to be sure.

**Comment by dominichayesferen** [comment]
@Elbullazul The Global Dark Theme uses another GTK theme file, gtk-contained-dark.css and/or gtk-dark.css... So if you fix it, then that's dark mode done...

**Comment by Elbullazul** [comment]
@brandleesee you have to manually disable dark theme in apps (ex. rythmbox, photos, terminal, etc.)

**Comment by brandleesee** [comment]
@Elbullazul case closed then, I didn't realise that they were manual. I just checked the preferences in Terminal and spot on there was a Theme 'Variant'. Thanks. :)

**Comment by Elbullazul** [comment]
fixed all text and menu padding issues :)

only need to darken progressbar and we're ready to go live (again!)

**Comment by brandleesee** [comment]
My testing environment is up and running again.

![screenshot from 2016-11-02 13-23-52](https://cloud.githubusercontent.com/assets/12674437/19928775/5904bfe0-a100-11e6-8a12-e7aeb333b88d.png)
Can a sort of padding be added between the radio button and text?

That and the same glow as before (my opinion).

**Comment by Elbullazul** [comment]
ok, we'll fix it soon

**Comment by ghost** [comment]
Try to patch paading into modelbutton > radio .
label modelbutton might get errors. not sure tough. my idea might or might
not work.

**Comment by Elbullazul** [comment]
found how to correct this, pushing commit soon...

**Comment by Elbullazul** [comment]
bug should be corrected @brandleesee @bluedxca93 

just the glow thing still to be fixed

**Comment by Elbullazul** [comment]
fixed the glow issue to use dark colors on both variants
