### ISSUE TITLE
Check marks look weird after latest commits

### ISSUE THREAD

**Issue by Vistaus** [B00merang-Project/Chrome-OS#7]
See the attached screenshot. Hope this can be fixed :)

OS: Arch Linux
GTK: 3.22.x
![screenshot from 2016-11-10 21-02-20](https://cloud.githubusercontent.com/assets/1716229/20192274/7c902e4c-a789-11e6-86e3-f9ca6b254602.png)

**Comment by Elbullazul** [comment]
oops, thanks for the bug report, we'll have a look at this

**Comment by Elbullazul** [comment]
it's now fixed

**Comment by Vistaus** [comment]
It's fixed indeed! Thanks for the quick fix! :smile:
