### ISSUE TITLE
Theme broken on Xfce 4.12

### ISSUE THREAD

**Issue by HeikoAdams** [B00merang-Project/Chrome-OS#8]
The theme seems to be broken on Xfce 4.12. GTK+3 is 3.22, GTK+2 is 2.24.31 and murrine engine is 0.98.2.

![bildschirmfoto_2016-11-18_19-55-50](https://cloud.githubusercontent.com/assets/1418818/20442545/4235052e-adc9-11e6-85d6-cfdcd1158160.png)

**Comment by Elbullazul** [comment]
Thanks for your comment. Unfortunately I'm out of service for a couple of weeks.  I'll try to fix this when I'll have time

**Comment by Elbullazul** [comment]
@HeikoAdams does this still happen?

**Comment by HeikoAdams** [comment]
Last time i tried (beginning of dec '16) yes. ATM I'm using Gnome 3.22 for business jobs so I can't test current git master

**Comment by HeikoAdams** [comment]
Okay I found it: The theme is broken on Xfce 4.12 if the (gtk2-) theme is installed under ~/.local/share/themes moving the theme to ~/.themes solves the problem

**Comment by Elbullazul** [comment]
@HeikoAdams older xfce builds read themes from .local?

glad it works

**Comment by HeikoAdams** [comment]
Yes. It's listed in the appearance settings if it's installed at .local - maybe because of the gtk3 parts of xfce
