### ISSUE TITLE
Android OS Theme on Ubuntu Gnome (devel branch)

### ISSUE THREAD

**Issue by brandleesee** [B00merang-Project/Chrome-OS#9]
## onmouseover

look at the minimize, maximize and close buttons

![](http://i.imgur.com/poYOsaG.gif)

## missing icons

![](http://i.imgur.com/28egp1K.png)

![](http://i.imgur.com/UdmfWkN.png)

## terminal

Are white borders around window and scroll bar intentional?

![](http://i.imgur.com/VAaJ06o.png)

**Comment by Elbullazul** [comment]
@brandleesee icons are a separate issue, remebmer their color is white?

thanks for the other reports, I'll correct them ASAP

**Comment by brandleesee** [comment]
Ah, yes! Must I report the icons somewhere else?

As is my usual I submit bug reports whenever I encounter them.

**Comment by brandleesee** [comment]
Re: icons, can you suggest an icon pack that goes well with Android OS, cheers!

**Comment by dominichayesferen** [comment]
@brandleesee Icon Pack: Paper or Papirus?

**Comment by brandleesee** [comment]
I'll check them both. As you can see I am not much of a fan of icon themes which is why I did not realise that the icons were invisible because I was using the W-clones. My interest lies more in way of the themes themselves.

**Comment by Elbullazul** [comment]
@brandleesee I think I fixed the titlebutton bg color bug, can you confirm?

**Comment by brandleesee** [comment]
onmousehover there is very little color change I get two shades of dark(er) green

**Comment by Elbullazul** [comment]
@brandleesee can you post screenshot please? I think I know what the bug is...

**Comment by Elbullazul** [comment]
@brandleesee I changed colors for hover/checked states, bug should be fixed
